name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
